### PR TITLE
fix(local): skip OS environment for detached processes

### PR DESCRIPTION
**Pull request by jbrockopp**
Part of the effort for https://github.com/go-vela/community/issues/54

I was playing around with the CLI locally trying to run pipelines on my workstation.

I noticed that when I was running `services` with a specific `image` that I would get errors trying to execute them.

Here is a snippet from the pipeline I was using:

```yaml
services:
  - name: postgres
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: somePassword
      POSTGRES_USER: example
    image: postgres:latest
    ports:
      - "5432:5432"
    pull: not_present
```

The error message I was getting looks like this:

```
[service: postgres] /usr/local/bin/docker-entrypoint.sh: line 82: initdb: command not found
```

At first I thought I was crazy because I had previously tested running `services` locally with other images:

```yaml
services:
  - name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    pull: not_present
```

And:

```yaml
services:
  - name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    pull: not_present
```

After some digging, it turns out that injecting the OS environment variables for `services` can cause issues.

From what I saw, if your OS environment contains "system" level variables like `USER`, `HOME`, `PATH` etc. that can cause a conflict and overwrite the defaults provided in an image that depends on those i.e. `postgres`

The reason this wasn't caught earlier is most of my testing involved using the `mongo` and `redis` images.

I found it best to skip injecting OS environment variables all together, for anything under the `services` section of YAML.

EDIT:

Like @davidvader pointed out, this also exists for `steps` with `detach: true` as that is functionally equivalent to `services`.

I've augmented this to no longer inject OS environment variables if a step is setup to run in a detached mode.

### CODE REVIEW

**Comment by davidvader** [comment]
does the same occur for step images that use system variables such as `PATH` ?
https://github.com/go-vela/compiler/blob/e3e30fec5ef6ac7d385188b209007806249d4b4c/compiler/native/environment.go#L57-L66
For example if I wanted to use `postgres` with `detach: true`? Would the same issue occur?

**Comment by davidvader** [comment]
have we considered making this.... optional? sort of like `docker run` and the `-e` flag?

**Comment by jbrockopp** [comment]
> does the same occur for step images that use system variables such as `PATH` ?
> https://github.com/go-vela/compiler/blob/e3e30fec5ef6ac7d385188b209007806249d4b4c/compiler/native/environment.go#L57-L66
> 
> 
> For example if I wanted to use `postgres` with `detach: true`? Would the same issue occur?

Yes that is correct 👍

**Comment by jbrockopp** [comment]
@davidvader I believe I have updated the PR to address your feedback 👍

**Review by davidvader — APPROVED** [review]

**Review by matt-fevold — APPROVED** [review]

**Pull request merged**
